# Generated by Django 4.1 on 2022-09-29 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('registration_year', models.PositiveIntegerField(default=1)),
                ('variant', models.CharField(max_length=200)),
                ('owner', models.CharField(max_length=200)),
                ('fuel', models.CharField(max_length=200)),
                ('kilometres', models.PositiveIntegerField(default=1)),
                ('gear_type', models.CharField(max_length=200)),
                ('price', models.PositiveIntegerField(default=1)),
                ('colour', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200)),
                ('rating', models.PositiveIntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.vehicles')),
            ],
        ),
    ]
